### ISSUE TITLE
Unable to send message, need help

### ISSUE THREAD

**Issue by Vaib215** [livekit/client-sdk-react-native#90] opened 2023-08-03 12:28 UTC
**Unable to send message**

I am trying to send message through this function but unable to send.
```
async function sendMessage(message: string) {
  try {
    if (message.length > 0) {
      let encoder = new TextEncoder();
      let data = encoder.encode(JSON.stringify({ message }));
      await room.localParticipant.publishData(data, DataPacket_Kind.RELIABLE);
      setMessage('');
    }
  } catch (e) {
    console.log(e);
  }
}
```

this is the log of the message on the web client for the message that are successfully visible, sent from another instance of web client
```
[
 0: {
  from: RemoteParticipant {/*user details*/},
  message: "Hello",
  timestamp: 1691064504917
  }
]
```

**Comment by Vaib215** [comment] 2023-08-04 12:25
yes, the admin is sending the message

**Comment by Vaib215** [comment] 2023-08-04 12:25
actually every participant in our meeting is given right to publish data

**Comment by Vaib215** [comment] 2023-08-04 12:27
I am getting the data on the peer indeed but the catch is that the format which the web client requires to parse the decoded message does not match to that of the one sent by the app.

this is the code of our web client chat
```
export function useChat() {
  const room = useRoomContext();
  const [setup, setSetup] = React.useState<ReturnType<typeof setupChat>>();
  const isSending = useObservableState(setup?.isSendingObservable, false);
  const chatMessages = useObservableState(setup?.messageObservable, []);

  React.useEffect(() => {
    const setupChatReturn = setupChat(room);
    setSetup(setupChatReturn);
    return setupChatReturn.destroy;
  }, [room]);

  return { send: setup?.send, chatMessages, isSending };
}

/**
 * The Chat component adds a basis chat functionality to the LiveKit room. The messages are distributed to all participants
 * in the room. Only users who are in the room at the time of dispatch will receive the message.
 *
 * @example
 * ```tsx
 * <LiveKitRoom>
 *   <Chat />
 * </LiveKitRoom>
 * ```
 * @public
 */
export function Chat({ messageFormatter, showChat, ...props }: ChatProps) {
  const inputRef = React.useRef<HTMLInputElement>(null);
  const ulRef = React.useRef<HTMLUListElement>(null);
  const { send, chatMessages, isSending } = useChat();

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    if (inputRef.current && inputRef.current.value.trim() !== "") {
      if (send) {
        await send(inputRef.current.value);
        inputRef.current.value = "";
        inputRef.current.focus();
      }
    }
  }

  React.useEffect(() => {
    if (ulRef) {
      ulRef.current?.scrollTo({ top: ulRef.current.scrollHeight });
    }
  }, [ulRef, chatMessages]);

  return (
    <div
      style={{ display: `${(!showChat && "none") || "flex"}` }}
      // {...props}
      className="lk-chat max-w-[100%] h-[100%] md:max-w-[380px]"
    >
      <div className="lk-chat w-full relative h-full">
        <div className=" absolute z-20 h-[100px] bg-gradient-to-b from-[#1e1e1e] to-[#1e1e1e]/0 w-full inset-x-0 top-3" />
        <ul
          className="h-full flex flex-col gap-3 overflow-y-scroll p-3 mt-5 relative"
          ref={ulRef}
        >
          {/* <div className="absolute h-[100px] bg-gradient-to-b from-[#1e1e1e] to-[#1e1e1e]/0 w-full inset-x-0 top-3" /> */}
          {props.children
            ? chatMessages.map((msg, idx) =>
              cloneSingleChild(props.children, {
                entry: msg,
                key: idx,
                messageFormatter,
              })
            )
            : chatMessages.map((msg, idx, allMsg) => {
              const hideName = idx >= 1 && allMsg[idx - 1].from === msg.from;
              // If the time delta between two messages is bigger than 60s show timestamp.
              const hideTimestamp =
                idx >= 1 &&
                msg.timestamp - allMsg[idx - 1].timestamp < 60_000;

              return (
                <ChatEntry
                  index={idx}
                  key={idx}
                  hideName={hideName}
                  hideTimestamp={hideName === false ? false : hideTimestamp} // If we show the name always show the timestamp as well.
                  entry={msg}
                  messageFormatter={messageFormatter}
                />
              );
            })}
        </ul>
        <form className="lk-chat-form" onSubmit={handleSubmit}>
          <input
            className="lk-form-control lk-chat-form-input"
            disabled={isSending}
            ref={inputRef}
            type="text"
            placeholder="Enter a message..."
          />
          <button
            type="submit"
            className="lk-button lk-chat-form-button"
            disabled={isSending}
          >
            Send
          </button>
        </form>
      </div>
    </div>
  );
}
```

**Comment by lukasIO** [comment] 2023-08-04 15:06
Ah, you mean it doesn't display in the `Chat` component ?
That's expected. `publishData` is a lower level method than the `send` method of the chat component in `components-react`. 

You'll just have to make sure that the message you send via `publishData` has the same format as the `ChatMessage` in the `components-react` package and send it with the same `topic`. Have a look at the the components-js `useChat` hook source code to see what's required. 
Feel free to ask questions in our community slack. 
Will close this, as it's not a bug.

**Closed as completed by lukasIO** 2023-08-04 15:06 UTC
Labels: bug
